apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
        - name: container
          image: >-
            #default-route-openshift-image-registry.apps.stgocp.mwanitest.local/{{ .Release.Namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
            default-route-openshift-image-registry.apps.stgocp.mwanitest.local/devops/poc-devops:latest
          ports:
            - containerPort: 8080
              protocol: TCP
